# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab6/lab6.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6 || ORIG_REF_NAME==lab6}]

# IP: bd/lab6/ip/lab6_processing_system7_0_0/lab6_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_processing_system7_0_0 || ORIG_REF_NAME==lab6_processing_system7_0_0}]

# IP: bd/lab6/ip/lab6_me_match_0_0/lab6_me_match_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_me_match_0_0 || ORIG_REF_NAME==lab6_me_match_0_0}]

# IP: bd/lab6/ip/lab6_ps7_0_axi_periph_0/lab6_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab6_ps7_0_axi_periph_0}]

# IP: bd/lab6/ip/lab6_rst_ps7_0_100M_0/lab6_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab6_rst_ps7_0_100M_0}]

# IP: bd/lab6/ip/lab6_auto_pc_0/lab6_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab6_auto_pc_0 || ORIG_REF_NAME==lab6_auto_pc_0}]

# XDC: bd/lab6/lab6_ooc.xdc
